# Generated by Django 4.1.6 on 2023-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_opt_in_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='frozen_balance',
            field=models.IntegerField(default=0),
        ),
    ]
