# Generated by Django 4.1.6 on 2023-02-19 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_user_biography_user_frozen_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_in_emails',
            new_name='opt_in_emails_application',
        ),
        migrations.AddField(
            model_name='user',
            name='opt_in_site_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='opt_in_site_application',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('seen', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
