# Generated by Django 4.1.6 on 2023-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='link',
            field=models.URLField(),
        ),
    ]
