# Generated by Django 4.1.6 on 2023-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_notifications_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_in_emails',
            new_name='opt_in_emails_application',
        ),
        migrations.AddField(
            model_name='user',
            name='opt_in_site_applicants',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='opt_in_site_application',
            field=models.BooleanField(default=True),
        ),
    ]
