# Generated by Django 4.1.2 on 2023-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_rename_opt_in_emails_user_opt_in_emails_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
