# Generated by Django 4.1.6 on 2023-02-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_rename_opt_in_emails_user_opt_in_emails_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_in_site_applicants',
            new_name='opt_in_site_applicant',
        ),
    ]
