# Generated by Django 4.1.6 on 2023-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_user_profile_id_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Alert', max_length=50),
        ),
    ]
