# Generated by Django 4.1.6 on 2023-03-01 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_of_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
