# Generated by Django 4.1.3 on 2023-03-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_notification_time_of_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="super_user",
            field=models.BooleanField(default=False),
        ),
    ]
