# Generated by Django 4.1.7 on 2023-03-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_remove_user_rating_user_charity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('time_of_notification',)},
        ),
    ]
