# Generated by Django 4.1.6 on 2023-03-02 11:07

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(upload_to=store.models.item_picture_rename),
        ),
    ]
