# Generated by Django 4.1.6 on 2023-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_item_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
