# Generated by Django 4.1.7 on 2023-02-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_rename_notifications_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_in_emails',
            new_name='opt_in_emails_application',
        ),
        migrations.AddField(
            model_name='user',
            name='opt_in_site_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='opt_in_site_application',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(),
        ),
    ]
