# Generated by Django 4.1.2 on 2023-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_notification_time_of_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
    ]
