# Generated by Django 4.1.6 on 2023-03-15 12:02

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_alter_notification_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=userprofile.models.profile_id_rename),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('profile_id', ''), ('charity', True)), models.Q(('charity', False), models.Q(('profile_id', ''), _negated=True)), _connector='OR'), name='profile_id_for_charities'),
        ),
    ]
