# Generated by Django 4.1.6 on 2023-03-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_alter_user_profile_id_user_profile_id_for_charities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-time_of_notification',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='super_user',
            new_name='guardian',
        ),
    ]
