# Generated by Django 4.1.6 on 2023-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_alter_notification_content_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
