# Generated by Django 4.1.6 on 2023-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limit_per_user',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
