# Generated by Django 4.1.3 on 2023-03-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_picture",
            field=models.ImageField(blank=True, upload_to="storeitem/"),
        ),
    ]
