# Generated by Django 4.1.6 on 2023-03-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('store', '0006_sale_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
                ('bank', models.IntegerField(default=0)),
                ('chat_deletion', models.BooleanField(default=True)),
            ],
        ),
    ]
