# Generated by Django 4.1.3 on 2023-03-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_application_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("superadmin", "0002_alter_report_last_update_time_alter_report_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConflictResolution",
            fields=[
                ("conflict_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
                (
                    "conflict_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "conflict_update_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Flagged", "Flagged"),
                            ("Resolved", "Reesolved"),
                        ],
                        default="Open",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Conflict1", "Conflict1"),
                            ("Conflict2", "Conflict2"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.job",
                    ),
                ),
                (
                    "user1_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
