# Generated by Django 4.1.6 on 2023-03-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_report_report_id_report_id'),
        ('superadmin', '0003_reportticket_conflictresolution'),
    ]

    operations = [
    ]
