# Generated by Django 4.1.6 on 2023-03-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_reportticket_conflictresolution'),
        ('superadmin', '0004_remove_report_id_report_report_id'),
    ]

    operations = [
    ]
