# Generated by Django 4.1.6 on 2023-03-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_remove_conflictresolution_conflict_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictresolution',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reportticket',
            name='id',
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='conflict_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportticket',
            name='ticket_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
