# Generated by Django 4.1.6 on 2023-03-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_remove_report_id_report_report_id'),
        ('superadmin', '0005_remove_conflictresolution_conflict_id_and_more'),
    ]

    operations = [
    ]
