# Generated by Django 4.1.6 on 2023-03-09 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_application_status'),
        ('superadmin', '0006_merge_20230309_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictresolution',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reportticket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reportticket',
            name='time_resolved',
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='conflict_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportticket',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('RE', 'Resolved')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='reportticket',
            name='ticket_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='last_update_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='reportticket',
            name='answer',
            field=models.CharField(blank=True, choices=[('BA', 'Ban'), ('NB', 'Not_Ban')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reportticket',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.report'),
        ),
    ]
