# Generated by Django 4.1.6 on 2023-03-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_reportticket_conflictresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='answer',
            field=models.CharField(blank=True, choices=[('BA', 'Ban'), ('NB', 'Not_Ban')], default=None, max_length=2, null=True),
        ),
    ]
