# Generated by Django 4.1.2 on 2022-10-17 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=7)),
                ('job_title', models.CharField(max_length=50)),
                ('job_short_description', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=1000)),
                ('posting_time', models.DateTimeField()),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('assigned', models.BooleanField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
