# Generated by Django 4.1.2 on 2022-11-09 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=8)),
                ('job_title', models.CharField(max_length=50)),
                ('job_short_description', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=1000)),
                ('posting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSaveForLater',
            fields=[
                ('save_for_later_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saving_time', models.DateTimeField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('job_process_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('RE', 'Rejected'), ('AC', 'Accepted')], default='AP', max_length=2)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usersaveforlater',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='sfl_user_job_combo'),
        ),
        migrations.AddConstraint(
            model_name='jobprocess',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='process_user_job_combo'),
        ),
    ]
