# Generated by Django 4.1.2 on 2022-11-10 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprocess',
            name='time_of_application',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='time_of_final_status',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jobprocess',
            name='status',
            field=models.CharField(choices=[('AP', 'Applied'), ('RE', 'Rejected'), ('AC', 'Accepted'), ('WD', 'Withdrawn'), ('DN', 'Done'), ('CO', 'Conflict')], default='AP', max_length=2),
        ),
    ]
