# Generated by Django 4.1.2 on 2022-11-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobprocess_time_of_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
