# Generated by Django 4.1.2 on 2022-10-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_alter_jobposting_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSaveForLater',
            fields=[
                ('save_for_later_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saving_time', models.DateTimeField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('job_process_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('RE', 'Rejected'), ('AC', 'Accepted')], default='AP', max_length=2)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usersaveforlater',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='sfl_user_job_combo'),
        ),
        migrations.AddConstraint(
            model_name='jobprocess',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='process_user_job_combo'),
        ),
    ]
