# Generated by Django 4.1.2 on 2022-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobposting_deadline'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobprocess',
            name='process_user_job_combo',
        ),
        migrations.RemoveConstraint(
            model_name='usersaveforlater',
            name='sfl_user_job_combo',
        ),
        migrations.RenameField(
            model_name='jobprocess',
            old_name='user_id',
            new_name='applicant_id',
        ),
        migrations.RenameField(
            model_name='jobprocess',
            old_name='job_process_id',
            new_name='application_id',
        ),
        migrations.RenameField(
            model_name='usersaveforlater',
            old_name='save_for_later_id',
            new_name='bookmark_id',
        ),
        migrations.AddConstraint(
            model_name='jobprocess',
            constraint=models.UniqueConstraint(fields=('applicant_id', 'job_id'), name='application_user_job_combo'),
        ),
        migrations.AddConstraint(
            model_name='usersaveforlater',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='bookmark_user_job_combo'),
        ),
    ]
