# Generated by Django 4.1.6 on 2023-02-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_short_description',
        ),
    ]
