# Generated by Django 4.1.2 on 2022-11-17 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_remove_jobprocess_process_user_job_combo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobProcess',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='UserSaveForLater',
            new_name='Bookmark',
        ),
        migrations.RenameModel(
            old_name='JobPosting',
            new_name='Job',
        ),
    ]
