# Generated by Django 4.1.2 on 2022-10-31 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userextended_usersaveforlater_jobprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
