# Generated by Django 4.1.2 on 2022-11-22 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_jobprocess_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='saving_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
