# Generated by Django 4.1.2 on 2022-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_userextended_balance_alter_userextended_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
