# Generated by Django 4.1.2 on 2022-11-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobposting_deadline_jobposting_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtended',
        ),
    ]
