# Generated by Django 4.1.6 on 2023-02-13 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=1000)),
                ('reporting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_time', models.DateTimeField(default=None)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ticketed', 'Ticketed'), ('Resolved', 'Resolved')], max_length=10)),
                ('type', models.CharField(choices=[('Profile', 'Profile'), ('Comment', 'Comment'), ('Job', 'Job'), ('Chat', 'Chat')], max_length=10)),
                ('reported_job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
