# Generated by Django 4.1.6 on 2023-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_update_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Ticketed', 'Ticketed'), ('Resolved', 'Resolved')], default='Open', max_length=10),
        ),
    ]
