# Generated by Django 4.1.6 on 2023-03-09 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_application_status'),
        ('superadmin', '0005_merge_20230309_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictresolution',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='conflictresolution',
            name='user1_id',
        ),
        migrations.DeleteModel(
            name='ReportTicket',
        ),
        migrations.AlterField(
            model_name='report',
            name='last_update_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.DeleteModel(
            name='ConflictResolution',
        ),
    ]
